# Checkov Security Configuration for Strimzi Kafka Helm Chart
# This file configures security scanning rules and exceptions for the Helm chart

# Framework configuration
framework:
  - kubernetes
  - helm

# Skip specific checks that are not applicable to Kafka/Strimzi deployments
skip-check:
  # Skip checks for resources that are managed by Strimzi Operator
  - CKV_K8S_8   # Liveness probe - managed by Strimzi
  - CKV_K8S_9   # Readiness probe - managed by Strimzi
  - CKV_K8S_10  # CPU requests - managed by Strimzi
  - CKV_K8S_11  # CPU limits - managed by Strimzi
  - CKV_K8S_12  # Memory requests - managed by Strimzi
  - CKV_K8S_13  # Memory limits - managed by Strimzi
  
  # Skip checks for Kafka-specific configurations
  - CKV_K8S_20  # Containers should not run as root - Kafka requires specific user
  - CKV_K8S_23  # Minimize the admission of root containers - Kafka specific requirements
  - CKV_K8S_25  # Minimize the admission of containers with allowPrivilegeEscalation - Kafka requirements
  
  # Skip checks for StatefulSet-specific configurations (managed by Strimzi)
  - CKV_K8S_38  # Ensure that Service Account Tokens are only mounted where necessary
  - CKV_K8S_40  # Containers should run as a high UID to avoid host conflicts
  
  # Skip network policy checks (environment-specific)
  - CKV_K8S_19  # Ensure that default service accounts are not actively used
  - CKV_K8S_21  # The default namespace should not be used

# Compact output for CI/CD
compact: true

# Quiet mode (reduce verbose output)
quiet: false