{{- if .Values.kafkaUsers }}
{{- range .Values.kafkaUsers }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "strimzi-kafka.labels" $ | nindent 4 }}
spec:
  {{- if .authentication }}
  authentication:
    type: {{ .authentication.type }}
    {{- if .authentication.password }}
    password:
      valueFrom:
        secretKeyRef:
          name: {{ .authentication.password.secretName }}
          key: {{ .authentication.password.key }}
    {{- end }}
  {{- end }}
  {{- if .authorization }}
  authorization:
    type: {{ .authorization.type }}
    {{- if .authorization.acls }}
    acls:
      {{- range .authorization.acls }}
      - resource:
          type: {{ .resource.type }}
          name: {{ .resource.name | quote }}
          patternType: {{ .resource.patternType }}
        operations:
          {{- range .operations }}
          - {{ . | quote }}
          {{- end }}
        host: {{ .host | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .quotas }}
  quotas:
    {{- if .quotas.producerByteRate }}
    producerByteRate: {{ .quotas.producerByteRate }}
    {{- end }}
    {{- if .quotas.consumerByteRate }}
    consumerByteRate: {{ .quotas.consumerByteRate }}
    {{- end }}
    {{- if .quotas.requestPercentage }}
    requestPercentage: {{ .quotas.requestPercentage }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}