{{- if .Values.kafkaTopics }}
{{- range .Values.kafkaTopics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "strimzi-kafka.labels" $ | nindent 4 }}
    strimzi.io/cluster: {{ include "strimzi-kafka.clusterName" $ }}
  {{- with $.Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .partitions }}
  partitions: {{ .partitions }}
  {{- end }}
  {{- if .replicas }}
  replicas: {{ .replicas }}
  {{- end }}
  {{- if .config }}
  config:
    {{- toYaml .config | nindent 4 }}
  {{- end }}
  {{- if .topicName }}
  topicName: {{ .topicName }}
  {{- end }}
{{- end }}
{{- end }}